// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHMc0gU83kHzRU8_--VgV1N07fN6apso',
    appId: '1:576308070342:web:8c62a26860155cb15614c7',
    messagingSenderId: '576308070342',
    projectId: 'todolist-a4e73',
    authDomain: 'todolist-a4e73.firebaseapp.com',
    storageBucket: 'todolist-a4e73.appspot.com',
    measurementId: 'G-81N7KXJXG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Kdzuv8JBjMejULtVFU_UaNv7J1BWEBM',
    appId: '1:576308070342:android:4efe2b1090ff9ce45614c7',
    messagingSenderId: '576308070342',
    projectId: 'todolist-a4e73',
    storageBucket: 'todolist-a4e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFmZx4VNwFRihY4ddKJK-KwY8_9vPWrzc',
    appId: '1:576308070342:ios:a3ed8f174eca1b965614c7',
    messagingSenderId: '576308070342',
    projectId: 'todolist-a4e73',
    storageBucket: 'todolist-a4e73.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFmZx4VNwFRihY4ddKJK-KwY8_9vPWrzc',
    appId: '1:576308070342:ios:a1bffcc379033e7a5614c7',
    messagingSenderId: '576308070342',
    projectId: 'todolist-a4e73',
    storageBucket: 'todolist-a4e73.appspot.com',
    iosBundleId: 'com.example.taskManager.RunnerTests',
  );
}
